#!/bin/sh -x

# vivirt --name n -c CPUs -m 1g

# CPUs
# cpus.count or cpus (single parameter)
# name= or name.name=
# memory=N or memory.kb=N or memory.gb=N
D=${0%/*}
cat "$D"/skeleton.xml \
  | xsltproc --stringparam name  "${NAME_NAME?}" "$D"/name.xsl - \
  | xsltproc --stringparam kb  "${MEMORY_KB}" --stringparam mb  "${MEMORY_MB}" --stringparam gb  "${MEMORY_GB}" "$D"/memory.xsl - \
  | xsltproc --stringparam count "${CPUS_COUNT-1}" "$D"/cpu.xsl - \
  | xsltproc "$D"/graphics.xsl - \
  | xsltproc "$D"/console.xsl - \
  | if [ -n "$CDROM" ]; then
	xsltproc --stringparam file "$CDROM" "$D"/cdrom.xsl -
    else cat; fi \
  | xmllint --format - \
  | tee result.xml
